# Generated by Django 4.1.2 on 2022-10-19 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('estiamflixx', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='realisateur',
            new_name='adresse_mail',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='description',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='user',
            name='annee_de_sortie',
        ),
        migrations.RemoveField(
            model_name='user',
            name='nbre_episodes',
        ),
        migrations.AddField(
            model_name='user',
            name='mdp',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
